config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants do 
    resources :reviews
  end

  resources :reviews do
    resources :usefuls
  end

    root "restaurants#index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  has_many :reviews, dependent: :destroy

  validates :name, length: {minimum: 3, message: "The restaurant name is too short"}, 
    uniqueness: {message: "Restaurants must have a unique name"}

  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :restaurant

  validates :rating, inclusion: { in: (1..5).to_a }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:twitter, :facebook]

  def self.from_omniauth_twitter(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      p auth.info
      user.email = auth.info.nickname+"@twitter.com"
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.from_omniauth_facebook(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params[:restaurant].permit(:name, :description))
      if @restaurant.save
        redirect_to restaurants_path
      else
        render 'new'
      end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    restaurant = Restaurant.find(params[:id])
    restaurant.update(params[:restaurant].permit(:name, :description))
    redirect_to restaurants_path
  end

  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.destroy
    flash[:notice] = 'Restaurant deleted'
    redirect_to restaurants_path
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    restaurant.reviews.create(params[:review].permit(:review, :rating))
    redirect_to restaurants_path
  end
end

app/controllers/usefuls_controller.rb
class UsefulsController < ApplicationController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth_twitter(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

 def facebook
    @user = User.from_omniauth_facebook(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

  def star_rating(rating)
        return rating unless rating.respond_to?(:round)
        remainder = (5 - rating)
        "★" * rating.round + "☆" * remainder
    end
end

app/helpers/usefuls_helper.rb
module UsefulsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %>
    <%= link_to "Sign up", new_user_registration_path %>
  <% end %>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.haml
-if @restaurant.errors.any?
  %h2= pluralize(@restaurant.errors.count, 'error')
  %ul
    -@restaurant.errors.full_messages.each do |message|
      %li=message
=form_for @restaurant do |f|
  =f.label :name
  =f.text_field :name
  =f.label :description
  =f.text_field :description
  =f.submit 'Submit restaurant'

app/views/restaurants/edit.html.haml
=render 'form'

app/views/restaurants/index.html.haml
-if @restaurants.any?
  -@restaurants.each do |restaurant|
    %h2= link_to restaurant.name, restaurant_path(restaurant)
    -restaurant.reviews.each do |review|
      %ul
        %li #{review.review}. Rating: #{review.rating} posted about #{time_ago_in_words(review.created_at)} ago
        =link_to "Useful", review_usefuls_path(review.id)
    %h3 Average rating: #{star_rating(restaurant.average_rating)}
    =link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    =link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    =link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
-else 
  %h2 No restaurants found

=link_to 'Add a restaurant', new_restaurant_path

app/views/restaurants/new.html.haml
=form_for @restaurant do |f|
  =f.label :name
  =f.text_field :name
  =f.label :description
  =f.text_field :description
  =f.submit 'Submit restaurant'

app/views/restaurants/show.html.haml
=@restaurant.name

=@restaurant.description

-@restaurant.reviews.each do |review|
  %ul
    %li #{review.review}. Rating: #{review.rating} posted about #{time_ago_in_words(review.created_at)} ago

%h3 Average rating: #{star_rating(@restaurant.average_rating)}

=link_to "Return to restaurants", restaurants_path

app/views/reviews/new.html.haml
=form_for [@restaurant, @review] do |f|
  =f.label :review, 'Your review' 
  =f.text_area :review
  =f.label :rating
  =f.select :rating, (1..5)
  =f.submit 'Leave review' 